// <auto-generated />
using HomeBase.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HomeBase.Migrations.RealEstate
{
    [DbContext(typeof(RealEstateContext))]
    [Migration("20180711194836_usahomessales")]
    partial class usahomessales
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("HomeBase.Models.USAHomeSales", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("finalsalesprice");

                    b.Property<DateTime>("insertionDate");

                    b.Property<string>("listingprice");

                    b.Property<string>("notes");

                    b.Property<string>("parsedhomeID");

                    b.Property<DateTime>("snapshotdate");

                    b.Property<string>("snapshottype");

                    b.HasKey("ID");

                    b.ToTable("USAHomeSales");
                });
#pragma warning restore 612, 618
        }
    }
}
