// <auto-generated />
using HomeBase.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace HomeBase.Migrations.FantasyZone
{
    [DbContext(typeof(FantasyZoneContext))]
    partial class FantasyZoneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("HomeBase.Models.FantasyWeekGames", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ATL_Games");

                    b.Property<int>("BKN_Games");

                    b.Property<int>("BOS_Games");

                    b.Property<int>("CHA_Games");

                    b.Property<int>("CHI_Games");

                    b.Property<int>("CLE_Games");

                    b.Property<int>("DAL_Games");

                    b.Property<int>("DEN_Games");

                    b.Property<int>("Det_Games");

                    b.Property<int>("GSW_Games");

                    b.Property<int>("HOU_Games");

                    b.Property<int>("IND_Games");

                    b.Property<int>("LAC_Games");

                    b.Property<int>("LAL_Games");

                    b.Property<int>("MEM_Games");

                    b.Property<int>("MIA_Games");

                    b.Property<int>("MIL_Games");

                    b.Property<int>("MIN_Games");

                    b.Property<int>("NOP_Games");

                    b.Property<int>("NYK_Games");

                    b.Property<int>("OKC_Games");

                    b.Property<int>("ORL_Games");

                    b.Property<int>("PHI_Games");

                    b.Property<int>("PHO_Games");

                    b.Property<int>("POR_Games");

                    b.Property<int>("SAC_Games");

                    b.Property<int>("SAS_Games");

                    b.Property<int>("TOR_Games");

                    b.Property<int>("UTA_Games");

                    b.Property<int>("WAS_Games");

                    b.Property<string>("WeekNumber")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("ID");

                    b.ToTable("FantasyWeekGames");
                });
#pragma warning restore 612, 618
        }
    }
}
